### PR TITLE
implemented psalm, cs-check, static analysis & fixed psalm errors

### LINKED ISSUE #12: Code quality

### LINKED ISSUE #14: green badge
https://insight.symfony.com/projects/a0d7016e-fc3f-46b8-9b36-571ff060d744

[SymfonyInsight](https://insight.symfony.com/projects/a0d7016e-fc3f-46b8-9b36-571ff060d744)

### PR DESCRIPTION
**Pull request by OnitaAndrei**

### CODE REVIEW

File: src/Factory/AbstractAnnotatedFactory.php [hunk 1]
```diff
@@ -18,28 +17,19 @@
...
- * Class AbstractAnnotatedFactory
- * @package Dot\AnnotatedServices\Factory
- */
 abstract class AbstractAnnotatedFactory
 {
-    const CACHE_SERVICE = 'Dot\AnnotatedServices\Cache';
+    protected const CACHE_SERVICE = 'Dot\AnnotatedServices\Cache';
 
     /** @var  Reader */
     protected $annotationReader;
```
Comment (alexmerlin) [inline src/Factory/AbstractAnnotatedFactory.php]: Please use inline property type declaration (not comment).

File: src/Factory/AnnotatedServiceAbstractFactory.php [hunk 2]
```diff
@@ -1,41 +1,38 @@
...
  */
 
-declare(strict_types = 1);
+declare(strict_types=1);
 
 namespace Dot\AnnotatedServices\Factory;
 
 use Dot\AnnotatedServices\Annotation\Service;
-use Interop\Container\ContainerInterface;
+use interop\container\containerinterface;
```
Comment (alexmerlin) [inline src/Factory/AnnotatedServiceAbstractFactory.php]: First, this should not be lowercase - not sure why you changed it.
Second, it should be:
`use Psr\Container\ContainerInterface;`
Please change and test. If I'm wrong, then let's keep the old version:
`use Interop\Container\ContainerInterface;`

File: src/Factory/AnnotatedServiceAbstractFactory.php [hunk 3]
```diff
@@ -1,41 +1,38 @@
...
- */
 class AnnotatedServiceAbstractFactory extends AbstractAnnotatedFactory implements AbstractFactoryInterface
 {
     /**
-     * @param ContainerInterface $container
      * @param string $requestedName
      * @return bool
      */
-    public function canCreate(ContainerInterface $container, $requestedName)
+    public function canCreate(containerinterface $container, $requestedName)
```
Comment (alexmerlin) [inline src/Factory/AnnotatedServiceAbstractFactory.php]: Please remove the method's docblock comments and add return type hinting.

File: src/Factory/AnnotatedServiceAbstractFactory.php [hunk 4]
```diff
@@ -46,12 +43,11 @@ public function canCreate(ContainerInterface $container, $requestedName)
...
 
     /**
-     * @param ContainerInterface $container
      * @param string $requestedName
      * @param array|null $options
-     * @return mixed
+     * @return object
      */
-    public function __invoke(ContainerInterface $container, $requestedName, array $options = null)
+    public function __invoke(containerinterface $container, $requestedName, ?array $options = null)
```
Comment (alexmerlin) [inline src/Factory/AnnotatedServiceAbstractFactory.php]: Please remove the method's docblock comment and add return type hinting (if possible).

File: src/Factory/AnnotatedServiceFactory.php [hunk 5]
```diff
@@ -19,44 +19,43 @@
...
     /**
-     * @param ContainerInterface $container
-     * @param $requestedName
      * @return mixed
      * @throws ContainerExceptionInterface
      * @throws NotFoundExceptionInterface
      * @throws ReflectionException
      */
-    public function __invoke(ContainerInterface $container, $requestedName)
+    public function __invoke(ContainerInterface $container, string $requestedName)
```
Comment (alexmerlin) [inline src/Factory/AnnotatedServiceFactory.php]: Please remove `return mixed` from the the method's docblock and add return type hinting.

File: src/Factory/AnnotatedServiceFactory.php [hunk 6]
```diff
@@ -19,44 +19,43 @@
...
     /**
-     * @param ContainerInterface $container
-     * @param $requestedName
      * @return mixed
      * @throws ContainerExceptionInterface
      * @throws NotFoundExceptionInterface
      * @throws ReflectionException
      */
-    public function createObject(ContainerInterface $container, $requestedName)
+    public function createObject(ContainerInterface $container, string $requestedName)
```
Comment (alexmerlin) [inline src/Factory/AnnotatedServiceFactory.php]: Please remove `return mixed` from the method's docblock and add return type hinting.

File: src/Factory/AnnotatedServiceFactory.php [hunk 7]
```diff
@@ -126,29 +123,26 @@ protected function getServicesToInject(ContainerInterface $container, Inject $in
 
     /**
      * @param array $keys
-     * @param $array
      * @return mixed
      */
-    protected function readKeysFromArray(array $keys, $array)
+    protected function readKeysFromArray(array $keys, mixed $array)
```
Comment (alexmerlin) [inline src/Factory/AnnotatedServiceFactory.php]: Please remove the method's docblock comment and add return type hinting.

File: tests/AnnotatedRepositoryFactoryTest.php [hunk 8]
```diff
@@ -27,9 +27,9 @@ public function setUp(): void
     {
         parent::setUp();
```
Comment (alexmerlin) [inline tests/AnnotatedRepositoryFactoryTest.php]: You can remove the call to `parent::setUp();,` because it does nothing.
The `setUp` method in `TestCase` is there only to make sure that the method is callable before each test, even if a test does not implement it.

File: phpunit.xml [hunk 9]
```diff
@@ -0,0 +1,14 @@
+<?xml version="1.0" encoding="UTF-8"?>
+<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/10.2/phpunit.xsd" bootstrap="./vendor/autoload.php" colors="true">
+    <testsuites>
+        <testsuite name="dot-user-agent-sniffer Test Suite">
```
Comment (alexmerlin) [inline phpunit.xml]: Please fix the test suite name.

File: composer.json [hunk 10]
```diff
@@ -40,8 +42,24 @@
...
+        "cs-fix": "phpcbf",
+        "test": "phpunit --colors=always",
+        "test-coverage": "phpunit --colors=always --coverage-clover clover.xml",
+        "static-analysis": "psalm --shepherd --stats"
+    },
     "suggest": {
         "doctrine/cache": "To cache the result of processing the annotations and speed-up your application.",
         "doctrine/orm": "To be able to inject doctrine repositories."
+    },
+    "config": {
```
Comment (alexmerlin) [inline composer.json:55]: Not a requirement, rather a nice-to-have, but for consistency across all our packages, let's add under the `config` section:
`"sort-packages": true,`

**Review by alexmerlin — CHANGES_REQUESTED** [review]
Please fix the following items:
1. Make sure there is an empty line at the end of each the following files:
* `.github/workflows/cs-tests.yml`
* `.github/workflows/static-analysis.yml`
* `.github/workflows/unit-tests.yml`
* `phpcs.xml`
* `phpunit.xml`
* `psalm.xml`
In case that they already have an empty line at the end, make sure the line endings are set to `LF` (NOT `CRLF`).
2. I know that the project initially contained a `tests` directory, but for consistency across all our packages, let's keep the tests in the `test` directory (make sure you change the directory name, in `composer.json`, `phpcs.xml` and in `phpunit.xml`).
3. All file header blocks should be removed:
> /**
>  * @see https://github.com/dotkernel/dot-annotated-services/ for the canonical source repository
>  */
4. Please add test for ConfigProvider (see [dot-geoip](https://github.com/dotkernel/dot-geoip/blob/3.0/test/ConfigProviderTest.php) or [dot-cli](https://github.com/dotkernel/dot-cli/blob/3.0/test/ConfigProviderTest.php)).

**Comment by alexmerlin** [comment]
Also, please add Symfony Insight badge.
If you don't have the snippet for it, ask @arhimede to create it.

File: composer.json [hunk 11]
```diff
@@ -20,15 +20,17 @@
...
         "laminas/laminas-servicemanager": "^3.10",
         "doctrine/annotations": "^1.13",
         "doctrine/cache": "^1.13",
         "doctrine/orm" : "^2.11"
     },
     "require-dev": {
-        "phpunit/phpunit": "^9.5",
-        "squizlabs/php_codesniffer": "^3.6"
+        "phpunit/phpunit": "^10.2",
+        "squizlabs/php_codesniffer": "^3.6",
```
Comment (alexmerlin) [inline composer.json]: Please remove this dependency, as it is also required by `laminas/laminas-coding-standard`.

File: src/Factory/AnnotatedServiceAbstractFactory.php [hunk 12]
```diff
@@ -1,41 +1,33 @@
...
 
-/**
- * Class AnnotatedServiceAbstractFactory
- * @package Dot\AnnotatedServiced\Factory
- */
 class AnnotatedServiceAbstractFactory extends AbstractAnnotatedFactory implements AbstractFactoryInterface
 {
     /**
-     * @param ContainerInterface $container
      * @param string $requestedName
```
Comment (alexmerlin) [inline src/Factory/AnnotatedServiceAbstractFactory.php:17]: Please remove this one as well.

File: src/Factory/AnnotatedServiceAbstractFactory.php [hunk 13]
```diff
@@ -46,12 +38,10 @@ public function canCreate(ContainerInterface $container, $requestedName)
     }
 
     /**
```
Comment (alexmerlin) [inline src/Factory/AnnotatedServiceAbstractFactory.php:40]: Please remove this one as well.

File: src/Factory/AnnotatedServiceFactory.php [hunk 14]
```diff
@@ -91,8 +84,6 @@ public function createObject(ContainerInterface $container, $requestedName)
     }
 
     /**
-     * @param ContainerInterface $container
-     * @param Inject $inject
      * @return array
```
Comment (alexmerlin) [inline src/Factory/AnnotatedServiceFactory.php]: Please remove this one as well.

File: src/Factory/AnnotatedServiceFactory.php [hunk 15]
```diff
@@ -126,29 +117,25 @@ protected function getServicesToInject(ContainerInterface $container, Inject $in
 
     /**
```
Comment (alexmerlin) [inline src/Factory/AnnotatedServiceFactory.php]: Please remove this one as well.

File: test/ConfigProviderTest.php [hunk 16]
```diff
@@ -0,0 +1,28 @@
...
+    }
+
+    public function testHasDependencies(): void
+    {
+        $this->assertArrayHasKey('dependencies', $this->config);
+    }
+
+    public function testDependenciesHasFactories(): void
+    {
+        $this->assertArrayHasKey('abstract_factories', $this->config['dependencies']);
```
Comment (alexmerlin) [inline test/ConfigProviderTest.php:27]: Please also make sure that `abstract_factories` contains `AnnotatedServiceAbstractFactory`.

File: composer.json [hunk 17]
```diff
@@ -37,11 +38,28 @@
...
+            "@cs-check",
+            "@test"
+        ],
+        "cs-check": "phpcs",
+        "cs-fix": "phpcbf",
+        "test": "phpunit --colors=always",
+        "test-coverage": "phpunit --colors=always --coverage-clover clover.xml",
+        "static-analysis": "psalm --shepherd --stats"
+    },
     "suggest": {
```
Comment (alexmerlin) [inline composer.json]: Please remove the `suggest` section completely, becuase the suggested packages are already in the `require` section.

**Review by alexmerlin — CHANGES_REQUESTED** [review]

**Review by alexmerlin — APPROVED** [review]
